server:
  port: 5700

spring:
  profiles:
    active: dev
  application:
    name: ray-wing-blog


# http://localhost:5700/v3/api-docs/swagger-ui.html
# http://localhost:5700/swagger-ui/index.html
springdoc:
  swagger-ui:
    display-request-duration: true
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    use-root-path: true
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /v3/api-docs
    groups:
      enabled: true
  show-actuator: true
  group-configs:
    - group: 文章管理
      paths-to-match: /article/**
    - group: 目录管理
      paths-to-match: /catalog/**
  cache:
    disabled: true