
spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5437/raywing_blog
    username: postgres
    password: wrp@PGatSMGI0601
    hikari:
      connection-timeout: 30000
      idle-timeout: 30000
      max-lifetime: 120000
      maximum-pool-size: 32
      minimum-idle: 8
      auto-commit: true

logging:
  level:
    com:
      wrp:
        user: debug
ray-wing:
  system:
    base-path: E:\temp\raywing
