server:
  port: 80

# mysql
spring:
  datasource:
    url: jdbc:postgresql://10.62.119.226:5437/raywing_blog
    username: postgres
    password: wrp@PGatSMGI0601
    hikari:
      connection-timeout: 30000
      idle-timeout: 30000
      max-lifetime: 120000
      maximum-pool-size: 32
      minimum-idle: 8
      auto-commit: true



  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

#mongodb:
#  host: localhost
#  port: 27017
#  auth: false #是否使用密码验证
#  username: tincery
#  password: renren
#  source: 123456
#  database: test

mybatis-plus:
  mapperLocations: classpath:mapper/**/*.xml


#指定数据库，可选值有【mysql、oracle、sqlserver、postgresql、mongodb】
renren:
  database: postgresql

